# Generated by Django 5.0.1 on 2024-01-15 15:38

import WebSite.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FamousPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('age', models.IntegerField(blank=True, null=True, validators=[WebSite.models.validate_age], verbose_name='Возраст')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Фото')),
                ('slug', models.SlugField(max_length=20, null=True, unique=True, verbose_name='URL')),
                ('time_creating', models.DateTimeField(auto_now=True, verbose_name='Время создания')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WebSite.categoryperson')),
            ],
            options={
                'ordering': ['-time_creating'],
                'indexes': [models.Index(fields=['slug', '-time_creating'], name='WebSite_fam_slug_9fdfd2_idx')],
            },
        ),
    ]
